apiVersion: apps/v1
kind: Deployment
metadata:
  name: template-api-gke
  namespace: "default"
  labels:
    app: "template-api-gke"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: template-api-gke
  template:
    metadata:
      labels:
        app: template-api-gke
    spec:
      volumes:
        - name: gcp-sa
          secret:
            secretName: gcp-sa
      containers:
        - name: template-api-gke
          image: "asia-east1-docker.pkg.dev/aiii-developer/develop/template-api-gke:0.0.0"
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: gcp-sa
              mountPath: "/etc/gcp-sa"
              readOnly: true
          env:
            - name: GOOGLE_APPLICATION_CREDENTIALS
              value: "/etc/gcp-sa/gcp-sa-ce-aiii-developer.json"
          envFrom:
            - configMapRef:
                name: stage-aiii-env
            - secretRef:
                name: stage-api-key
          resources:
            limits:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
            requests:
              cpu: 500m
              ephemeral-storage: 1Gi
              memory: 2Gi
