ABS_PATH=$(pwd)
export INTERNAL_API_KEY=AIzaSyBzhcGkiS-SBWDSc4UF4mqeYKxLZ6SvZyA
export APIs_api=https://api-v2-5uvz3vc6ga-de.a.run.app
export APIs_platformPush=https://platform-push-v1-5uvz3vc6ga-de.a.run.app
export APIs_platformPushAudienceClient=https://platform-push-audience-client-5uvz3vc6ga-de.a.run.app
export APIs_basicWebhook=https://prod-line-dialogflow-5uvz3vc6ga-de.a.run.app
export APIs_bottery_lottery01=https://api-lottery-01-5uvz3vc6ga-de.a.run.app
export APIs_bottery_lottery02=https://api-lottery-02-5uvz3vc6ga-de.a.run.app
export APIs_bottery_lottery03=https://api-lottery-03-5uvz3vc6ga-de.a.run.app
export APIs_bottery_lottery04=https://api-lottery-04-5uvz3vc6ga-de.a.run.app
export APIs_bottery_lottery05=https://api-lottery-05-5uvz3vc6ga-de.a.run.app
export APIs_couponOnline=https://api-coupon-online-5uvz3vc6ga-de.a.run.app
export APIs_recommendation=https://recommendation-5uvz3vc6ga-de.a.run.app
export APIs_membership=https://api-member-form-5uvz3vc6ga-de.a.run.app
export GKE_Interal_base_url=https://stage-internal-api.aiii.ai
export Internal_url=https://stage-internal.aiii.ai
export pubSub_topic_path=projects/aiii-bot-platform/topics/log-firestore-to-big-query
export firestorTwUrl=https://aiii-developer-tw.firebaseio.com
export firestorUsUrl=https://aiii-developer.firebaseio.com
export fireStorageTwBucket=gs://aiii-developer-tw.appspot.com
export TW_FIREBASE_CERTIFICATE_PATH=projects/700749202278/secrets/tw-dev-firebase-service-account/versions/1
export GOOGLE_CLOUD_PROJECT=aiii-developer
export TZ=Asia/Taipei
export IS_DEV= true
